### ISSUE TITLE
use Drug Central CURIEs for drugs in KG-IDG

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-idg#46]
Incorporate SSSOM (https://github.com/mapping-commons/sssom) as part of KG-IDG metadata.

@justaddcoffee - you had some ideas regarding what this entails

**Comment by justaddcoffee** [comment]
@caufieldjh thanks for the ping. I think the action items here is "use Drug Central CURIEs for drugs in KG-IDG". (This I think is sensible because as @cmungall said, CHEBI IDs will often make distinctions between chemicals that are not important to us.

For example here's the CHEBI entry for [acetylsalicylic acid (aspirin) CHEBI:15365](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:15365) and here's a separate CHEBI entry for [acetylsalicylate CHEBI:13719](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:13719), which is the same drug except in the form that exists at high pH. For our purposes, these are the same thing. Drug Central has just [one entry for aspirin](https://drugcentral.org/drugcard/74?q=aspirin), which is nice for our use case.

SSSOM I think maybe can help us do this. The idea would be to construct tooling to make an SSSOM mapping file for all drugs we ingest that maps any drug ID -> Drug Central ID, and then apply this mapping to make KGX applies the mapping. 

Another strategy would be to just perform the mapping manually during each transform of the drug database. We'd just put the drug central CURIE in the node ID column, and put any other CURIEs (CHEBI, or whatever) in the `xref` column.

**Comment by caufieldjh** [comment]
Great - this is a dupe of #45 then, didn't know if you had plans for SSSOM beyond drug CURIE mapping

**Comment by caufieldjh** [comment]
I'm in favor of SSSOM for the sake of reusability (e.g., this probably won't be the last time we'll have CHEBI IDs but want to map to drugs, and for that matter perhaps some mappings for existing CHEBI xrefs like CHEMBL) though it seems like adding the xrefs during the transform may be faster to implement on its own and isn't incompatible with generating and using SSSOM maps.
